-- ==============================================================================
-- 💖 Aura AI 데이팅 (aura-ai-dating.vercel.app) 공식 Supabase DB 스키마
-- 대시보드: https://supabase.com/dashboard/project/ncflciezowwpnknuutko/sql
-- ==============================================================================

-- 1. Aura 공식 2030 매거진 & 블로그 아카이브 테이블 (aura_blogs)
CREATE TABLE IF NOT EXISTS public.aura_blogs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic_id INT NOT NULL,
    category VARCHAR(64) NOT NULL,
    category_name VARCHAR(128) NOT NULL,
    title_naver TEXT NOT NULL,
    title_tistory TEXT NOT NULL,
    title_kakao TEXT NOT NULL,
    title TEXT NOT NULL,
    excerpt TEXT,
    content_md TEXT NOT NULL,
    content_html TEXT NOT NULL,
    thumbnail_url TEXT,
    visual_prompt TEXT,
    tags TEXT[],
    landing_url TEXT DEFAULT 'https://aura-ai-dating.vercel.app/',
    views INT DEFAULT 0,
    likes INT DEFAULT 0,
    translations JSONB DEFAULT '{}'::jsonb,
    published_at TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 기존 테이블이 이미 생성된 경우를 위한 translations 컬럼 추가 DDL
ALTER TABLE public.aura_blogs ADD COLUMN IF NOT EXISTS translations JSONB DEFAULT '{}'::jsonb;

-- 2. 고속 검색용 인덱스 설정
CREATE INDEX IF NOT EXISTS idx_aura_blogs_topic_id ON public.aura_blogs(topic_id);
CREATE INDEX IF NOT EXISTS idx_aura_blogs_category ON public.aura_blogs(category);
CREATE INDEX IF NOT EXISTS idx_aura_blogs_created_at ON public.aura_blogs(created_at DESC);

-- 3. RLS(Row Level Security) 보안 정책 활성화
ALTER TABLE public.aura_blogs ENABLE ROW LEVEL SECURITY;

-- 익명/일반 사용자 읽기 허용 정책
DROP POLICY IF EXISTS "Allow public read access to aura_blogs" ON public.aura_blogs;
CREATE POLICY "Allow public read access to aura_blogs"
    ON public.aura_blogs
    FOR SELECT
    TO anon, authenticated
    USING (true);

-- 익명/봇 쓰기 허용 정책
DROP POLICY IF EXISTS "Allow public insert access to aura_blogs" ON public.aura_blogs;
CREATE POLICY "Allow public insert access to aura_blogs"
    ON public.aura_blogs
    FOR INSERT
    TO anon, authenticated
    WITH CHECK (true);

-- 서비스 롤(봇) 전체 쓰기/수정 권한 정책
DROP POLICY IF EXISTS "Allow service role full access to aura_blogs" ON public.aura_blogs;
CREATE POLICY "Allow service role full access to aura_blogs"
    ON public.aura_blogs
    FOR ALL
    TO service_role
    USING (true)
    WITH CHECK (true);

-- ==============================================================================
-- 4. 라운지 실시간 피드(lounge_posts) 매거진 인덱스 보강 (선택사항)
-- ==============================================================================
CREATE INDEX IF NOT EXISTS idx_lounge_posts_category_created ON public.lounge_posts(category, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_lounge_posts_user_id ON public.lounge_posts(user_id);
